const actions = {
  SET_STATE: 'social/SET_STATE',
  LOAD_CURRENT_SOCIAL: 'social/LOAD_CURRENT_SOCIAL',
  FOLLOW_USER: 'social/FOLLOW_USER',
  UNFOLLOW_USER: 'social/UNFOLLOW_USER',
  ACCEPT_FOLLOW_REQUEST: 'social/ACCEPT_FOLLOW_REQUEST',
  REJECT_FOLLOW_REQUEST: 'social/REJECT_FOLLOW_REQUEST',
  CANCEL_FOLLOW_REQUEST: 'social/CANCEL_FOLLOW_REQUEST',
}

export default actions
