const actions = {
  SET_STATE: 'cart/SET_STATE',
  LOAD_CURRENT_CART: 'cart/LOAD_CURRENT_CART',
  ADD_COURSE_TO_CART: 'cart/ADD_COURSE_TO_CART',
  ADD_MENTORSHIP_LISTING_TO_CART: 'cart/ADD_MENTORSHIP_LISTING_TO_CART',
  DELETE_FROM_CART: 'cart/DELETE_FROM_CART',
  EMPTY_CART: 'cart/EMPTY_CART',
}

export default actions
