export const ADMIN_ROLE_ENUM = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  FINANCE: 'FINANCE',
}

export const ADMIN_VERIFIED_ENUM = {
  SHELL: 'SHELL',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  DRAFT: 'DRAFT',
}

export const DEFAULT_TIMEOUT = 550

export const DEFAULT_ITEMS_PER_PAGE = 10

export const MENTORSHIP_CONTRACT_APPROVAL = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

export const MONTH_NAMES = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
]

export const LEVEL_ENUM = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
}

export const PRIVACY_PERMISSIONS_ENUM = {
  FOLLOWING_ONLY: 'FOLLOWING_ONLY',
  ALL: 'ALL',
  NONE: 'NONE',
}

export const STATUS_ENUM = {
  ACTIVE: 'ACTIVE',
  BANNED: 'BANNED',
}

export const USER_TYPE_ENUM = {
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT',
  SENSEI: 'SENSEI',
}

export const USER_TYPE_STRING = {
  ADMIN: 'Admin',
  STUDENT: 'Student',
  SENSEI: 'Sensei',
}

export const VISIBILITY_ENUM = {
  PUBLISHED: 'PUBLISHED',
  HIDDEN: 'HIDDEN',
}

export const CONTRACT_PROGRESS_ENUM = {
  NOT_STARTED: 'NOT_STARTED',
  ONGOING: 'ONGOING',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
}

export const BILLING_TYPE = {
  INTERNAL: 'INTERNAL',
  COURSE: 'COURSE',
  MENTORSHIP: 'MENTORSHIP',
  REFUND: 'REFUND',
  WITHDRAWAL: 'WITHDRAWAL',
}

export const BILLING_STATUS_ENUM = {
  ADMIN: 'ADMIN',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
  PENDING_120_DAYS: 'PENDING_120_DAYS',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING_WITHDRAWAL: 'PENDING_WITHDRAWAL',
  REJECTED: 'REJECTED',
  SUCCESS: 'SUCCESS',
  WITHDRAWN: 'WITHDRAWN',
}

export const DIRECTION = {
  ASC: 'ASCENDING',
  DESC: 'DESCENDING',
}
