const actions = {
  SET_STATE: 'user/SET_STATE',
  LOGIN: 'user/LOGIN',
  REGISTER: 'user/REGISTER',
  LOGOUT: 'user/LOGOUT',
  CHANGE_PASSWORD: 'user/CHANGE_PASSWORD',
  LOAD_CURRENT_ACCOUNT: 'user/LOAD_CURRENT_ACCOUNT',
  GET_PROFILE: 'user/GET_PROFILE',
  UPDATE_PERSONAL_INFO: 'user/UPDATE_PERSONAL_INFO',
  DELETE_ACCOUNT: 'user/DELETE_ACCOUNT',
  UPDATE_ACCOUNT_SETTINGS: 'user/UPDATE_ACCOUNT_SETTINGS',
  UPDATE_ABOUT: 'user/UPDATE_ABOUT',
  UPDATE_WORK_DETAILS: 'user/UPDATE_WORK_DETAILS',
  UPDATE_PERSONALITY: 'user/UPDATE_PERSONALITY',
  UPDATE_ADMIN_VERIFIED: 'user/UPDATE_ADMIN_VERIFIED',
  ADD_EXPERIENCE: 'user/ADD_EXPERIENCE',
  EDIT_EXPERIENCE: 'user/EDIT_EXPERIENCE',
  DELETE_EXPERIENCE: 'user/DELETE_EXPERIENCE',
}

export default actions
