const actions = {
  SET_STATE: 'user/SET_STATE',
  LOAD_CURRENT_ACCOUNT: 'user/LOAD_CURRENT_ACCOUNT',
  LOGIN: 'user/LOGIN',
  REGISTER: 'user/REGISTER',
  LOGOUT: 'user/LOGOUT',
  CHANGE_PASSWORD: 'user/CHANGE_PASSWORD',
  DELETE_ACCOUNT: 'user/DELETE_ACCOUNT',
  UPDATE_PROFILE: 'user/UPDATE_PROFILE',
  ADD_EXPERIENCE: 'user/ADD_EXPERIENCE',
  EDIT_EXPERIENCE: 'user/EDIT_EXPERIENCE',
  DELETE_EXPERIENCE: 'user/DELETE_EXPERIENCE',
  DELETE_DP: 'user/DELETE_DP',
}

export default actions
