export const PASSWORDS_MISMATCH = 'Passwords do not match.'
export const ENSURE_PASSWORDS_MATCH = 'Please ensure both passwords match.'

export const ADMIN_DELETED = 'Administrator successfully deleted.'
export const ADMIN_DET_CHANGED = 'Administrator details were successfully updated.'
export const ADMIN_NAMES_CHANGED = 'Only Administrator names were updated.'
export const ADMIN_PERMISSIONS_CHANGED = 'Only Administrator permissions were updated.'

export const ASSESSMENT_VID_DELETE_ERR = 'There was an error deleting your assessment video.'
export const ASSESSMENT_VID_DELETE_SUCCESS = 'Your assessment video was successfully deleted.'
export const LESSON_UPDATE_SUCCESS = 'Your lesson was successfully updated.'
export const LESSON_UPDATE_ERR = 'There was an error updating your lesson.'
export const LESSON_DELETE_ERR = 'There was an error deleting your lesson.'
export const LESSON_DELETE_SUCCESS = 'Your lesson was successfully deleted.'
export const LESSON_VID_DELETE_SUCCESS = 'Your lesson video was successfully deleted.'
export const LESSON_VID_DELETE_ERR = 'There was an error deleting your lesson video.'

export const SUCCESS = 'Success'
export const ERROR = 'Error'
export const WARNING = 'Warning'
export const OOPS = 'Something went wrong.'
