export const PASSWORDS_MISMATCH = 'Passwords do not match.'
export const ENSURE_PASSWORDS_MATCH = 'Please ensure both passwords match.'

export const ADMIN_DELETED = 'Administrator successfully deleted.'
export const ADMIN_DET_CHANGED = 'Administrator details were successfully updated.'
export const ADMIN_NAMES_CHANGED = 'Only Administrator names were updated.'
export const ADMIN_PERMISSIONS_CHANGED = 'Only Administrator permissions were updated.'

export const COURSE_IMG_DEL_SUCCESS = 'Course Image removed successfully.'
export const COURSE_IMG_DEL_ERR = 'There was an error removing your course image.'
export const COURSE_ACCEPT_SUCCESS = 'The course request was successfully accepted.'
export const COURSE_ACCEPT_ERROR = 'There was an error accepting the course request.'
export const COURSE_REJECT_SUCCESS = 'The course request was successfully rejected.'
export const COURSE_REJECT_ERROR = 'There was an error rejecting the course request.'

export const ASSESSMENT_VID_DELETE_ERR = 'There was an error deleting your assessment video.'
export const ASSESSMENT_VID_DELETE_SUCCESS = 'Your assessment video was successfully deleted.'
export const ASSESSMENT_VID_ALR_PLAYING = 'Your assessment video is already playing.'
export const LESSON_UPDATE_SUCCESS = 'Your lesson was successfully updated.'
export const LESSON_UPDATE_ERR = 'There was an error updating your lesson.'
export const LESSON_DELETE_ERR = 'There was an error deleting your lesson.'
export const LESSON_DELETE_SUCCESS = 'Your lesson was successfully deleted.'
export const LESSON_VID_DELETE_SUCCESS = 'Your lesson video was successfully deleted.'
export const LESSON_VID_ALR_PLAYING = 'Your lesson video is already playing.'
export const LESSON_VID_DELETE_ERR = 'There was an error deleting your lesson video.'
export const LESSON_FILE_DELETE_SUCCESS = 'Your lesson file was successfully deleted.'
export const LESSON_FILE_DELETE_ERR = 'There was an error deleting your lesson file.'
export const LESSON_FILE_DOWNLOAD_ERR = 'There was an error downloading your file.'

export const COMMENT_ADD_SUCCESS = 'Your comment was successfully added.'
export const COMMENT_ADD_ERR = 'There was an error adding your comment.'
export const COMMENT_DEL_SUCCESS = 'Your comment was successfully deleted.'
export const COMMENT_DEL_ERR = 'There was an error deleting your comment.'

export const ANNOUNCEMENT_CREATED_SUCCESS = 'Your announcement was successfully added.'
export const ANNOUNCEMENT_CREATED_ERR = 'There was an error adding your announcement.'
export const ANNOUNCEMENT_EDIT_SUCCESS = 'Your announcement was successfully updated.'
export const ANNOUNCEMENT_EDIT_ERR = 'There was an error updating your announcement.'
export const ANNOUNCEMENT_DEL_SUCCESS = 'Your announcement was successfully deleted.'
export const ANNOUNCEMENT_DEL_ERR = 'There was an error deleting your announcement.'

export const ACCEPT_SENSEI_PROFILE = 'Sensei profile successfully accepted.'
export const REJECT_SENSEI_PROFILE = 'Sensei profile successfully rejected.'
export const SENSEI_PROFILE_UPDATE_ERR = "There was an error updating this Sensei's profile."

export const WITHDRAWAL_REQUEST_SUCCESS = 'Your withdrawal request was successfully sent.'
export const WITHDRAWAL_REQUEST_ERR = 'There was an error sending your withdrawal request.'

export const SUCCESS = 'Success'
export const ERROR = 'Error'
export const WARNING = 'Warning'
export const OOPS = 'Something went wrong.'

export const CART_EMPTY = 'You cannot checkout an empty cart.'
export const CART_ITEM_REMOVE = 'Your item was removed successfully.'
export const CART_COURSE_ADDED = 'Course successfully added to cart.'
export const CART_MENTORSHIP_ADDED = 'Mentorship successfully added to cart.'
export const MENTORSHIP_ADD = 'Mentorship Application successfully added to Cart'
export const UNABLE_ADD = 'Unable to add to Cart'
export const MENTORSHIP_ALR_IN = 'Mentorship Application is already in Cart'

export const DP_REMOVED = 'Your Display Picture was successfully removed.'
export const NO_DP_TO_REMOVE = 'No Display Picture to remove.'
