export const industry = [
  'Accounting',
  'Airlines/Aviation',
  'Alternative Dispute Resolution',
  'Alternative Medicine',
  'Animation',
  'Apparel & Fashion',
  'Architecture & Planning',
  'Arts & Crafts',
  'Automotive',
  'Aviation & Aerospace',
  'Banking',
  'Biotechnology',
  'Broadcast Media',
  'Building Materials',
  'Business Supplies & Equipment',
  'Capital Markets',
  'Chemicals',
  'Civic & Social Organization',
  'Civil Engineering',
  'Commercial Real Estate',
  'Computer & Network Security',
  'Computer Games',
  'Computer Hardware',
  'Computer Networking',
  'Computer Software',
  'Construction',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Services',
  'Cosmetics',
  'Dairy',
  'Defense & Space',
  'Design',
  'Education Management',
  'E-learning',
  'Electrical & Electronic Manufacturing',
  'Entertainment',
  'Environmental Services',
  'Events Services',
  'Executive Office',
  'Facilities Services',
  'Farming',
  'Financial Services',
  'Fine Art',
  'Fishery',
  'Food & Beverages',
  'Food Production',
  'Fundraising',
  'Furniture',
  'Gambling & Casinos',
  'Glass, Ceramics & Concrete',
  'Government Administration',
  'Government Relations',
  'Graphic Design',
  'Health, Wellness & Fitness',
  'Higher Education',
  'Hospital & Health Care',
  'Hospitality',
  'Human Resources',
  'Import & Export',
  'Individual & Family Services',
  'Industrial Automation',
  'Information Services',
  'Information Technology & Services',
  'Insurance',
  'International Affairs',
  'International Trade & Development',
  'Internet',
  'Investment Banking/Venture',
  'Investment Management',
  'Judiciary',
  'Law Enforcement',
  'Law Practice',
  'Legal Services',
  'Legislative Office',
  'Leisure & Travel',
  'Libraries',
  'Logistics & Supply Chain',
  'Luxury Goods & Jewelry',
  'Machinery',
  'Management Consulting',
  'Maritime',
  'Marketing & Advertising',
  'Market Research',
  'Mechanical or Industrial Engineering',
  'Media Production',
  'Medical Device',
  'Medical Practice',
  'Mental Health Care',
  'Military',
  'Mining & Metals',
  'Motion Pictures & Film',
  'Museums & Institutions',
  'Music',
  'Nanotechnology',
  'Newspapers',
  'Nonprofit Organization Management',
  'Oil & Energy',
  'Online Publishing',
  'Outsourcing/Offshoring',
  'Package/Freight Delivery',
  'Packaging & Containers',
  'Paper & Forest Products',
  'Performing Arts',
  'Pharmaceuticals',
  'Philanthropy',
  'Photography',
  'Plastics',
  'Political Organization',
  'Primary/Secondary',
  'Printing',
  'Professional Training',
  'Program Development',
  'Public Policy',
  'Public Relations',
  'Public Safety',
  'Publishing',
  'Railroad Manufacture',
  'Ranching',
  'Real Estate',
  'Recreational',
  'Facilities & Services',
  'Religious Institutions',
  'Renewables & Environment',
  'Research',
  'Restaurants',
  'Retail',
  'Security & Investigations',
  'Semiconductors',
  'Shipbuilding',
  'Sporting Goods',
  'Sports',
  'Staffing & Recruiting',
  'Supermarkets',
  'Telecommunications',
  'Textiles',
  'Think Tanks',
  'Tobacco',
  'Translation & Localization',
  'Transportation/Trucking/Railroad',
  'Utilities',
  'Venture Capital',
  'Veterinary',
  'Warehousing',
  'Wholesale',
  'Wine & Spirits',
  'Wireless',
  'Writing & Editing',
]

export const categories = {
  development: {
    categoryName: 'Development',
    subcategories: [
      'Web Development',
      'Data Science',
      'Mobile Development',
      'Programming Languages',
      'Game Development',
      'Database Design & Development',
      'Software Testing',
    ],
  },
  business: {
    categoryName: 'Business',
    subcategories: [
      'Entrepreneurship',
      'Communications',
      'Management',
      'Sales',
      'Business Strategy',
      'Operations',
      'Project Management',
      'Business Law',
      'Business Analytics & Intelligence',
    ],
  },
  'finance-accounting': {
    categoryName: 'Finance & Accounting',
    subcategories: [
      'Accounting & Bookkeeping',
      'Compliance',
      'Cryptocurrency & Blockchain',
      'Economics',
      'Finance',
      'Finance Cert & Exam Prep',
      'Financial Modeling & Analysis',
    ],
  },
  'it-software': {
    categoryName: 'IT & Software',
    subcategories: [
      'IT Certification',
      'Network & Security',
      'Hardware',
      'Operating Systems',
      'Other IT & Software',
    ],
  },
  'office-productivity': {
    categoryName: 'Office Productivity',
    subcategories: ['Microsoft', 'Apple', 'Google', 'SAP', 'Oracle', 'Other Office Productivity'],
  },
  'personal-development': {
    categoryName: 'Personal Development',
    subcategories: [
      'Personal Transformation',
      'Personal Productivity',
      'Leadership',
      'Career Development',
      'Parenting & Relationships',
      'Happiness',
      'Esoteric Practices',
      'Religion & Spirituality',
    ],
  },
  design: {
    categoryName: 'Design',
    subcategories: [
      'Web Design',
      'Graphic Design & Illustration',
      'Design Tools',
      'User Experience Design',
      'Game Design',
      'Design Thinking',
      '3D & Animation',
      'Fashion Design',
      'Architectural Design',
    ],
  },
  marketing: {
    categoryName: 'Marketing',
    subcategories: [
      'Digital Marketing',
      'Search Engine Optimization',
      'Branding',
      'Marketing Fundamentals',
      'Marketing Analytics & Automation',
      'Public Relations',
      'Advertising',
    ],
  },
  'health-fitness': {
    categoryName: 'Health & Fitness',
    subcategories: [
      'Fitness',
      'General Health',
      'Sports',
      'Nutrition',
      'Yoga',
      'Mental Health',
      'Dieting',
      'Self Defense',
      'Safety & First Aid',
      'Dance',
      'Meditation',
      'Other Health & Fitness',
    ],
  },
  music: {
    categoryName: 'Music',
    subcategories: [
      'Instruments',
      'Music Production',
      'Music Fundamentals',
      'Vocal',
      'Music Techniques',
      'Music Software',
      'Other Music',
    ],
  },
}
